"""Derive file projections from a ResearchPlan.

The DB is the source of record; these ``<plan_id>.json`` / ``<plan_id>.md``
files under ``research/plans/`` are **derived** views for diff/inspect and human
reading. Markdown is generated from the model — never authored as the primary
artifact.

**They are written once, at creation, and go stale immediately.**
`PlanStore.update_plan_status` writes the DB row only — it is the storage layer
and does not know about projections — and all five callers in `engineer.py` use
it, so every later transition to `in_progress` / `done` / `abandoned` lands in
the DB and nowhere else.

Measured on rogii 2026-08-08: the DB held ``done=16, abandoned=3`` while all
**19** projections said ``ready``. Not drift — none of them was ever right after
the plan first moved.

So each projection stamps its own provenance. Refreshing them on every
transition would push projection-writing down into the storage layer, and a
stale file that *looks* authoritative is the failure that actually happened —
twice. The evidence log records *"All 17 plans are stuck at `ready`; nothing
writes `done`"* as a misdiagnosis read off these files, and the same class of
read (`artifacts/evidence_card_*.json`, written by the builder and read by
nothing) produced a second one. Both were reasonable: 19 of 19 files agreed.

The stamp is what makes the next such read self-announcing.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from labpilot.research_engine.intelligence.paths import ResearchPaths
from labpilot.research_engine.planner.schemas.models import ResearchPlan

#: Key carrying the projection's own provenance. Leading underscore so it sorts
#: first and reads as metadata rather than as a plan field.
PROJECTION_KEY = "_projection"

_STALE_WARNING = (
    "Derived view, written when this plan was created and NOT refreshed "
    "afterwards. `status` here is the status at creation time; later "
    "transitions (in_progress/done/abandoned) exist only in the "
    "`research_plans` table. Query the DB before concluding anything about "
    "plan state."
)


def projection_stamp() -> dict[str, object]:
    """Provenance block marking this file as derived, not authoritative."""
    return {
        "authoritative": False,
        "source_of_record": "research_plans table in knowledge.db",
        "generated_at": datetime.now(UTC).isoformat(),
        "warning": _STALE_WARNING,
    }


def plan_to_json(plan: ResearchPlan) -> str:
    payload = {PROJECTION_KEY: projection_stamp()}
    payload.update(json.loads(plan.model_dump_json()))
    return json.dumps(payload, indent=2)


def render_markdown(plan: ResearchPlan) -> str:
    lines: list[str] = [
        f"# Research Plan {plan.id}",
        "",
        f"> Derived view, generated {datetime.now(UTC).isoformat()} and not",
        "> refreshed since. The `research_plans` table is the source of record;",
        "> **the status below is the status at creation time.**",
        "",
        f"- **Hypothesis:** {plan.hypothesis_id or '—'}",
        f"- **Competition:** {plan.competition or '—'}",
        f"- **Status (at creation):** {plan.status}",
        f"- **Generated by:** {plan.generated_by}",
    ]
    if plan.estimated_gain:
        lines.append(f"- **Estimated gain:** {plan.estimated_gain}")
    lines += [
        "",
        "## Goal",
        "",
        plan.goal or "—",
    ]
    if plan.current_state:
        lines += ["", "## Current state", "", plan.current_state]
    if plan.expected_outcome:
        lines += ["", "## Expected outcome", "", plan.expected_outcome]
    if plan.risk:
        lines += ["", "## Risk", "", plan.risk]

    lines += ["", "## Tasks", ""]
    for task in plan.tasks:
        deps = ", ".join(task.dependencies) if task.dependencies else "—"
        lines.append(f"### {task.id} · {task.type}")
        lines.append("")
        lines.append(task.description or "—")
        lines.append("")
        lines.append(f"- **Depends on:** {deps}")
        if task.verification.check:
            lines.append(f"- **Verify:** {task.verification.check}")
        if task.verification.failure_recovery:
            lines.append(f"- **Recovery:** {task.verification.failure_recovery}")
        if task.retry_policy.max_retries:
            lines.append(f"- **Retries:** {task.retry_policy.max_retries}")
        lines.append("")

    if plan.success_criteria:
        lines += ["## Success criteria", ""]
        lines += [f"- {item}" for item in plan.success_criteria]
        lines.append("")
    if plan.rollback:
        lines += ["## Rollback", "", plan.rollback, ""]
    return "\n".join(lines).rstrip() + "\n"


def write_projections(
    plan: ResearchPlan,
    *,
    knowledge_dir: Path,
    competition: str,
) -> tuple[Path, Path]:
    """Write ``<plan_id>.json`` and ``<plan_id>.md``; return their paths."""
    paths = ResearchPaths(knowledge_dir, competition)
    plans_dir = paths.plans_dir
    plans_dir.mkdir(parents=True, exist_ok=True)
    json_path = plans_dir / f"{plan.id}.json"
    md_path = plans_dir / f"{plan.id}.md"
    json_path.write_text(plan_to_json(plan) + "\n")
    md_path.write_text(render_markdown(plan))
    return json_path, md_path
