"""Derive file projections from a ResearchPlan.

The DB is the source of record; these ``<plan_id>.json`` / ``<plan_id>.md``
files under ``research/plans/`` are **derived** views for diff/inspect and human
reading. Markdown is generated from the model — never authored as the primary
artifact.
"""

from __future__ import annotations

from pathlib import Path

from labpilot.research_engine.intelligence.paths import ResearchPaths
from labpilot.research_engine.planner.schemas.models import ResearchPlan


def plan_to_json(plan: ResearchPlan) -> str:
    return plan.model_dump_json(indent=2)


def render_markdown(plan: ResearchPlan) -> str:
    lines: list[str] = [
        f"# Research Plan {plan.id}",
        "",
        f"- **Hypothesis:** {plan.hypothesis_id or '—'}",
        f"- **Competition:** {plan.competition or '—'}",
        f"- **Status:** {plan.status}",
        f"- **Generated by:** {plan.generated_by}",
    ]
    if plan.estimated_gain:
        lines.append(f"- **Estimated gain:** {plan.estimated_gain}")
    lines += [
        "",
        "## Goal",
        "",
        plan.goal or "—",
    ]
    if plan.current_state:
        lines += ["", "## Current state", "", plan.current_state]
    if plan.expected_outcome:
        lines += ["", "## Expected outcome", "", plan.expected_outcome]
    if plan.risk:
        lines += ["", "## Risk", "", plan.risk]

    lines += ["", "## Tasks", ""]
    for task in plan.tasks:
        deps = ", ".join(task.dependencies) if task.dependencies else "—"
        lines.append(f"### {task.id} · {task.type}")
        lines.append("")
        lines.append(task.description or "—")
        lines.append("")
        lines.append(f"- **Depends on:** {deps}")
        if task.verification.check:
            lines.append(f"- **Verify:** {task.verification.check}")
        if task.verification.failure_recovery:
            lines.append(f"- **Recovery:** {task.verification.failure_recovery}")
        if task.retry_policy.max_retries:
            lines.append(f"- **Retries:** {task.retry_policy.max_retries}")
        lines.append("")

    if plan.success_criteria:
        lines += ["## Success criteria", ""]
        lines += [f"- {item}" for item in plan.success_criteria]
        lines.append("")
    if plan.rollback:
        lines += ["## Rollback", "", plan.rollback, ""]
    return "\n".join(lines).rstrip() + "\n"


def write_projections(
    plan: ResearchPlan,
    *,
    knowledge_dir: Path,
    competition: str,
) -> tuple[Path, Path]:
    """Write ``<plan_id>.json`` and ``<plan_id>.md``; return their paths."""
    paths = ResearchPaths(knowledge_dir, competition)
    plans_dir = paths.plans_dir
    plans_dir.mkdir(parents=True, exist_ok=True)
    json_path = plans_dir / f"{plan.id}.json"
    md_path = plans_dir / f"{plan.id}.md"
    json_path.write_text(plan_to_json(plan) + "\n")
    md_path.write_text(render_markdown(plan))
    return json_path, md_path
